### ISSUE TITLE
ajax 프로그래밍 시 뒤로 가기 처리!

### ISSUE THREAD

**Issue by cheekee** [outsideris/request-blog-post#2]
저처럼 초급 개발자들이 궁금할 것 같은 이슈입니다.
'페이스북'처럼 목록이 로딩된 상태 (페이징 처리X) 에서 뒤로 가기 처리하는 방법에 대해서
정리해 주시면 도움이 많이 될 것 같습니다.

**Comment by outsideris** [comment]
요즘 모던 브라우저 대상이라면 pushState를 사용하는 것으로 알고 있는데 최근에 이부분을 직접 구현해 본적이 없기는 한데 흥미로운 주제라서 정리가능할지 확인해 보겠습니다. 이슈 남겨주셔서 감사합니다.

**Comment by wnghdcjfe** [comment]
저도 궁금합니다. ㅎ

**Comment by outsideris** [comment]
https://blog.outsider.ne.kr/1276
