### ISSUE TITLE
Outsider님이 블로그 포스팅을 하는 과정을 블로그 포스팅 해주세요!

### ISSUE THREAD

**Issue by kimdwkimdw** [outsideris/request-blog-post#3]
Outsider님이 블로그 포스팅을 하는 과정을 블로그 포스팅 해주세요!

많은 글들을 작성 하시는데 그 글들을 별도로 archive하시는지

이 글들을 작성하는데는 어떤 도구를

초안은 따로 적으시는지(예. 최근에 적은 글들??)

실제 글 작성하는데는 얼마나 걸리는지 궁금하네요 ㅎㅎ

"Outsider의 글쓰기" 같은 글?

**Comment by outsideris** [comment]
가끔 나누어서 얘기하거나 한적은 있는데 전체적으로 정리한적은 없네요. 항상 하던거라 정리만 잘하면 될것 같아서 긍정적으로 검토해보겠습니다. 의견 감사합니다.

**Comment by momamene** [comment]
이 주제 저도 궁금합니다! #4 와도 관련이 있을 수 있을 것 같은데요.

저도 블로그는 만들어 놨지만 이런 저런 이유로 포스팅을 계속 미루게 되는데 업무에 치여도 귀찮음과 피곤함을 극복하고 꾸준히 포스팅을 하는 습관이나 노하우를 공유해 주시면 좋을 것 같습니다.

**Comment by seoh** [comment]
off-topic 같기도 하지만 연관되는거 같아서 그냥 코멘트로 추가하자면, 정보를 얻는 경로와 수집 및 선별하는 도구, 읽는데 걸리는 시간이나 그 스케쥴 관리, 그리고 어떻게 인덱싱해서 소재로 사용되는지. 그 다음 과정은 이 이슈 본문에 해당하겠네요. 전체적인 과정이 궁금합니다.

**Comment by outsideris** [comment]
이 주제의 우선순위를 끌어올려야겠네요

**Comment by cheese10yun** [comment]
저도 궁금합니다. 꼭 다루어주세요

**Comment by wnghdcjfe** [comment]
오 좋습니다. ㅎ

**Comment by seoh** [comment]
독촉 기능 넣어주세요 :p

**Comment by outsideris** [comment]
쓰고 있긴한데 밀려서.. ㅠㅠ 
독촉은 댓글로 하시면 됩니다. ㅠㅠ 1월내 목표인데... 벌써.. 흑;

**Comment by seoh** [comment]
독촉은 농담이고 그냥 쓰고 계신건지 아니면 다른 것부터 쓰고 계신 것인지 궁금했습니다 :) 그러고보니 draft를 github에서
관리하시는 것도 어떤 과정으로 얼마나 걸리는지 가늠할만한 데이터가 될 것 같은데 어떠신가요?

**Comment by outsideris** [comment]
오래걸렸지만 https://blog.outsider.ne.kr/1269 에 글을 올렸습니다. 글감을 제안해 주셔서 감사합니다 ^^;;
추가로 궁금한 부분은 여기에 올려주셔도 되고 댓글에 써주셔도 되고요.
