### ISSUE TITLE
아웃사이더님의 시간관리 필승전략이 궁금합니다.

### ISSUE THREAD

**Issue by asbubam** [outsideris/request-blog-post#4]
개발 공부를 하다보면, 처음 생각과는 달리 삼천포로 빠질 때도 많고
꾸준히 진행하지 못하고 포기하는 경우도 많은데요.

아웃사이더님은 새로운 기술을 공부할 때, 어떤 방식으로 문제에 접근하시고
시간관리는 어떤 방식으로 하시는 지 궁금합니다.

아웃사이더님의 라이프해킹 특강!

**Comment by outsideris** [comment]
전 딱히 시간관리를 잘하고 있진 않은데 ㅠㅠ 곰곰히 생각해 보겠습니다. ㅎ

**Comment by outsideris** [comment]
시간관리는 딱히 하고 있지 않은 편이고 #3 의 글에서 관련내용이 약간 들어갔다고 생각해서 이 이슈는 일단 닫습니다. 다른 내용이 더 필요하시면 다른 이슈로 올려주셔도 되고요 ^^

**Comment by asbubam** [comment]
@outsideris 감사합니다. :)
