### ISSUE TITLE
개발자로서 아웃사이더님의 삶을 포스팅해줬으면 합니다

### ISSUE THREAD

**Issue by SongYunSeop** [outsideris/request-blog-post#5]
안녕하세요! 

아웃사이더님 블로그를 종종 눈팅하고 있는 초보개발자입니다 ㅎㅎ

왜 개발자가 되기로 했는지, 어떤 개발자가 되고 싶어했는지...

이제 막 개발을 시작하는 입장에서 아웃사이더님과 같은 개발자 분들의 이런 경험담은 많은 통찰을 줄 것 같아요

**Comment by qkrcjfgus33** [comment]
신입 개발자 혹은 길을 헤매는 개발자를 위해, 아웃사이더님의 길(방향)을 알고 싶습니다.
.. 부끄럽지만 지금 제가 헤매고 있는 졸업예정 개발자..입니다.

**Comment by outsideris** [comment]
이건 기술적이라기 보다는 좀 철학적(?)인 느낌이라 꽤 어렵네요. 
좀더 자세히 얘기해 주시면 글감을 정리할 때 도움이 될것 같습니다 ^^;;
